### ISSUE TITLE
Sample MP4 file in readme.

### ISSUE THREAD

**Issue by suriab** [OtherCrashOverride/c2play#21]
Can you add a link to Mp4 file (in readme) which you were able to play on Odroid C2 this shall help to reproduce the results. As there is so much content on internet due to differences in encoding it becomes difficult to conclude.  I am unable to play MP4 (AVC) with latest code on Odroid C2.

**Comment by OtherCrashOverride** [comment]
The "readme" is not really appropriate for content links since they are not under my control.  The owner of links could redirect them to anything they wish including inappropriate content or malware.

For testing of MP4 (container) with a H264(AVC) stream, you can try Big Buck Bunny:
http://bbb3d.renderfarming.net/download.html
http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4

For MP4 (container) with a MPEG4 stream, you may wish to try the latest updates in the "next" branch.

**Comment by suriab** [comment]
Agreed makes sense.

**Comment by OtherCrashOverride** [comment]
Since there is no action to be taken, I am closing this issue.  The MP4 linked above has been tested and works correctly with the current build.  Feel free to open a new issue if you experience problems with it.
